// Generated by https://quicktype.io

export interface Recipe {
  id:                  number;
  name:                string;
  cookTime:            string;
  prepTime:            string;
  totalTime:           string;
  level:               string;
  servings:            string;
  directions:          string;
  imageUrl:            string;
  linkedCategories:    LinkedCategory[];
  recipeToIngredients: RecipeToIngredient[];
}

export interface LinkedCategory {
  id:   number;
  name: string;
}

export interface RecipeToIngredient {
  ingredient:          Ingredient;
  usCustomaryWeight:   number;
  metricWeight:        number;
  usCustomaryUnitType: string;
  metricUnitType:      string;
  id:                  number;
}

export interface Ingredient {
  id:       number;
  name:     string;
  category: string;
}
